services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
       - /Users/navi/Desktop/City_Disaster/Sabhailte-Dublin/backend/database:/docker-entrypoint-initdb.d
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      API_KEY: ${API_KEY}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network

      #frontend:
      #build:
      #context: ./frontend
      #ports:
      #- "3000:3000"
      #networks:
      #- app-network

volumes:
  db_data:

networks:
  app-network:
