import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";
import AuthCheck from "./components/AuthCheck";
import admin from "firebase-admin";
import { getApps } from "firebase-admin/app";
import CustomNavbar from "./components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

if (!getApps().length) {
  admin.initializeApp({
    credential: admin.credential.cert({
      projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID,
      clientEmail: process.env.FIREBASE_CLIENT_EMAIL,
      privateKey: (process.env.FIREBASE_PRIVATE_KEY ?? "").replace(/\\n/g, "\n"),
    }),
  });
}

export const metadata: Metadata = {
  title: "Sabhailte Dublin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AuthCheck />
        <HeroUIProvider>
          <CustomNavbar />
          {children}
        </HeroUIProvider>
      </body>
    </html>
  );
}
