// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9aJVgoh5ZF_wcVS7V0XIdqCl3_PcJyDw',
    appId: '1:914170332121:web:69f7d2dd1eb24fbbed0fc8',
    messagingSenderId: '914170332121',
    projectId: 'sabhailte-dublin',
    authDomain: 'sabhailte-dublin.firebaseapp.com',
    storageBucket: 'sabhailte-dublin.firebasestorage.app',
    measurementId: 'G-JXJ5VHYSE9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwqNgsplNLS4jOrgnm2RaF7EzStt-BeQc',
    appId: '1:914170332121:android:310420090141eee4ed0fc8',
    messagingSenderId: '914170332121',
    projectId: 'sabhailte-dublin',
    storageBucket: 'sabhailte-dublin.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPkktmf8mP1Ocg5BnxAtE4bdhgIUWMOcs',
    appId: '1:914170332121:ios:b7581d2b6db68940ed0fc8',
    messagingSenderId: '914170332121',
    projectId: 'sabhailte-dublin',
    storageBucket: 'sabhailte-dublin.firebasestorage.app',
    iosBundleId: 'com.example.sabhailteDubin',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPkktmf8mP1Ocg5BnxAtE4bdhgIUWMOcs',
    appId: '1:914170332121:ios:da0e21d6bac5be36ed0fc8',
    messagingSenderId: '914170332121',
    projectId: 'sabhailte-dublin',
    storageBucket: 'sabhailte-dublin.firebasestorage.app',
    iosClientId: '914170332121-qqqv7862og33airobgeun0qg5hsqqk92.apps.googleusercontent.com',
    iosBundleId: 'com.navdeep.flutterAppmy',
  );

}
